/**
 * Mechanical Circulatory Support (MCS), Impella & LVAD Hemodynamics Models.
 *
 * Implements Society for Cardiovascular Angiography and Interventions (SCAI) Shock Staging,
 * Impella microaxial pump flow curves (P1-P9), HeartMate 3 centrifugal continuous-flow LVAD metrics,
 * Pulmonary Artery Pulsatility Index (PAPi) for RV failure detection, Cardiac Power Output (CPO),
 * and purge solution heparin/bivalirudin titration standards.
 */

export const SCAI_SHOCK_STAGES = Object.freeze({
  STAGE_E_EXTREMIS: {
    id: 'STAGE_E_EXTREMIS',
    label: 'SCAI Stage E (Extremis / Refractory Shock)',
    color: 'rose',
    priority: 1,
    description: 'Circulatory collapse requiring multiple mechanical circulatory support devices (e.g. Impella + VA-ECMO / ECPELLA) or active CPR.',
  },
  STAGE_D_DETERIORATING: {
    id: 'STAGE_D_DETERIORATING',
    label: 'SCAI Stage D (Deteriorating / Non-Responder)',
    color: 'orange',
    priority: 2,
    description: 'Failure to respond to initial MCS/inotropes; persistent hypoperfusion with escalating lactate and CPO < 0.6 W.',
  },
  STAGE_C_CLASSIC: {
    id: 'STAGE_C_CLASSIC',
    label: 'SCAI Stage C (Classic Cardiogenic Shock)',
    color: 'amber',
    priority: 3,
    description: 'Hypoperfusion requiring inotropes or temporary MCS (Impella CP / 5.5) to achieve MAP >= 65 mmHg and CI >= 2.2 L/min/m2.',
  },
  POST_IMPLANT_STABLE: {
    id: 'POST_IMPLANT_STABLE',
    label: 'Post-Implant Supported / Compensated',
    color: 'cyan',
    priority: 4,
    description: 'Adequately unloaded left ventricle on stable Impella/LVAD support with normal end-organ perfusion.',
  },
  WEANING_TRIAL_CANDIDATE: {
    id: 'WEANING_TRIAL_CANDIDATE',
    label: 'MCS Weaning & Recovery Candidate',
    color: 'emerald',
    priority: 5,
    description: 'Native myocardial recovery meeting step-down P-level criteria with CPO >= 0.8 W on minimal support (P2/P3).',
  },
});

export const MCS_DEVICE_TYPES = Object.freeze({
  IMPELLA_CP: {
    id: 'IMPELLA_CP',
    name: 'Impella CP with SmartAssist (Transfemoral 14 Fr)',
    maxFlowLitersMin: 4.0,
    cannulaSizeFr: 14,
    purgeFluidTarget: 'D5W with Heparin 25-50 U/mL (or Bivalirudin)',
    primaryIndication: 'Acute Myocardial Infarction Cardiogenic Shock (AMICS) & High-Risk PCI',
  },
  IMPELLA_5_5: {
    id: 'IMPELLA_5_5',
    name: 'Impella 5.5 with SmartAssist (Transaxillary Surgical 21 Fr)',
    maxFlowLitersMin: 5.5,
    cannulaSizeFr: 21,
    purgeFluidTarget: 'D5W with Heparin 25-50 U/mL',
    primaryIndication: 'Acute-on-Chronic Decompensated Heart Failure & Bridge to Decision/Transplant',
  },
  IMPELLA_RP: {
    id: 'IMPELLA_RP',
    name: 'Impella RP Flex (Right Ventricular Support 22 Fr)',
    maxFlowLitersMin: 4.0,
    cannulaSizeFr: 22,
    purgeFluidTarget: 'D5W with Heparin 50 U/mL',
    primaryIndication: 'Refractory Acute Right Heart Failure / Post-LVAD RV Failure',
  },
  HEARTMATE_3_LVAD: {
    id: 'HEARTMATE_3_LVAD',
    name: 'HeartMate 3 Left Ventricular Assist System (Fully MagLev)',
    maxFlowLitersMin: 10.0,
    cannulaSizeFr: 0,
    purgeFluidTarget: 'N/A (Driveline / Transcutaneous)',
    primaryIndication: 'End-Stage HFrEF (Bridge to Transplantation / Destination Therapy)',
  },
});

export const MCS_PATIENTS_DATABASE = Object.freeze([
  {
    id: 'MCS-401',
    mrn: 'MCS-891024',
    name: 'Julian Vance',
    ageYears: 58,
    sex: 'Male',
    heightCm: 178,
    actualWeightKg: 86.0,
    bodySurfaceAreaM2: 2.05,
    location: 'Cardiac Surgical ICU - Bed 01',
    primaryDiagnosis: 'Post-Cardiotomy Cardiogenic Shock s/p Emergent CABG & Mitral Repair',
    deviceType: 'IMPELLA_5_5',
    deviceLocation: 'Right Axillary Surgical Conduit',
    implantDurationHours: 72,
    scaiStage: 'STAGE_C_CLASSIC',
    pLevel: 'P7',
    impellaFlowLitersMin: 4.8,
    motorCurrentMilliamps: 710,
    purgePressureMmHg: 540,
    purgeFlowMlPerHour: 14.2,
    opticalPlacementSignal: 'CORRECT_LV_POSITION',
    lvadSpeedRpm: 0,
    lvadPowerWatts: 0,
    lvadPulsatilityIndex: 0,
    heartRate: 88,
    systolicBp: 104,
    diastolicBp: 68,
    meanArterialPressure: 80.0,
    cardiacOutputTotalLitersMin: 5.6,
    cardiacIndexLitersMinM2: 2.73,
    cardiacPowerOutputWatts: 0.99,
    pulmonaryArterySystolicBp: 34,
    pulmonaryArteryDiastolicBp: 18,
    centralVenousPressure: 12,
    pulmonaryArteryPulsatilityIndex: 1.33, // (34 - 18) / 12 = 1.33 (> 1.0 = RV stable)
    pulmonaryCapillaryWedgePressure: 16,
    lvedpEstimatedMmHg: 14,
    serumLactate: 1.4,
    plasmaFreeHemoglobinMgDl: 18.2, // Normal < 40
    ldhUnitsPerLiter: 290,
    antiXaUnitsPerMl: 0.35, // Target 0.3 - 0.5
    inotropesVasopressors: 'Epinephrine 0.02 mcg/kg/min • Vasopressin 0.03 U/min',
    suctionAlarmActive: false,
    weaningTrialStatus: 'Active Hemodynamic Unloading - Stable',
  },
  {
    id: 'MCS-402',
    mrn: 'MCS-662910',
    name: 'Evelyn St. Claire',
    ageYears: 62,
    sex: 'Female',
    heightCm: 160,
    actualWeightKg: 64.0,
    bodySurfaceAreaM2: 1.68,
    location: 'CCU / Cath Lab Recovery - Bed 04',
    primaryDiagnosis: 'Anterior STEMI Cardiogenic Shock with Refractory Ventricular Tachycardia',
    deviceType: 'IMPELLA_CP',
    deviceLocation: 'Right Femoral Artery 14 Fr',
    implantDurationHours: 18,
    scaiStage: 'STAGE_D_DETERIORATING',
    pLevel: 'P8',
    impellaFlowLitersMin: 3.4,
    motorCurrentMilliamps: 890, // High current / near suction
    purgePressureMmHg: 780, // High purge pressure warning
    purgeFlowMlPerHour: 6.8,
    opticalPlacementSignal: 'AORTIC_MIGRATION_WARNING',
    lvadSpeedRpm: 0,
    lvadPowerWatts: 0,
    lvadPulsatilityIndex: 0,
    heartRate: 118,
    systolicBp: 84,
    diastolicBp: 54,
    meanArterialPressure: 64.0,
    cardiacOutputTotalLitersMin: 3.8,
    cardiacIndexLitersMinM2: 2.26,
    cardiacPowerOutputWatts: 0.54, // Shock: CPO < 0.6 W
    pulmonaryArterySystolicBp: 44,
    pulmonaryArteryDiastolicBp: 26,
    centralVenousPressure: 20,
    pulmonaryArteryPulsatilityIndex: 0.90, // (44 - 26) / 20 = 0.90 (< 1.0 = RV failure risk)
    pulmonaryCapillaryWedgePressure: 24,
    lvedpEstimatedMmHg: 22,
    serumLactate: 3.6,
    plasmaFreeHemoglobinMgDl: 62.0, // Elevated hemolysis (> 40)
    ldhUnitsPerLiter: 640,
    antiXaUnitsPerMl: 0.22, // Subtherapeutic (< 0.3)
    inotropesVasopressors: 'Norepinephrine 0.12 mcg/kg/min • Milrinone 0.375 mcg/kg/min',
    suctionAlarmActive: true,
    weaningTrialStatus: 'Unstable - Suction & Repositioning Required',
  },
  {
    id: 'MCS-403',
    mrn: 'MCS-102948',
    name: 'Marcus Sterling',
    ageYears: 51,
    sex: 'Male',
    heightCm: 185,
    actualWeightKg: 95.0,
    bodySurfaceAreaM2: 2.18,
    location: 'Heart Failure ICU - Bed 07',
    primaryDiagnosis: 'Non-Ischemic Dilated Cardiomyopathy (Bridge to Heart Transplant)',
    deviceType: 'HEARTMATE_3_LVAD',
    deviceLocation: 'Left Ventricular Apex to Ascending Aorta',
    implantDurationHours: 360, // Post-Op Day 15
    scaiStage: 'POST_IMPLANT_STABLE',
    pLevel: 'N/A',
    impellaFlowLitersMin: 0,
    motorCurrentMilliamps: 0,
    purgePressureMmHg: 0,
    purgeFlowMlPerHour: 0,
    opticalPlacementSignal: 'N/A',
    lvadSpeedRpm: 5400,
    lvadPowerWatts: 4.8,
    lvadPulsatilityIndex: 3.8, // Normal 3.0 - 5.5
    heartRate: 76,
    systolicBp: 108,
    diastolicBp: 78,
    meanArterialPressure: 88.0,
    cardiacOutputTotalLitersMin: 5.4,
    cardiacIndexLitersMinM2: 2.48,
    cardiacPowerOutputWatts: 1.05,
    pulmonaryArterySystolicBp: 28,
    pulmonaryArteryDiastolicBp: 12,
    centralVenousPressure: 8,
    pulmonaryArteryPulsatilityIndex: 2.00, // (28 - 12) / 8 = 2.0 (Normal RV)
    pulmonaryCapillaryWedgePressure: 12,
    lvedpEstimatedMmHg: 10,
    serumLactate: 0.9,
    plasmaFreeHemoglobinMgDl: 12.0,
    ldhUnitsPerLiter: 210,
    antiXaUnitsPerMl: 0.42,
    inotropesVasopressors: 'None (Oral Heart Failure Meds Optimizing)',
    suctionAlarmActive: false,
    weaningTrialStatus: 'Stable Long-Term MCS Support',
  },
  {
    id: 'MCS-404',
    mrn: 'MCS-551920',
    name: 'Robert Thorne',
    ageYears: 67,
    sex: 'Male',
    heightCm: 172,
    actualWeightKg: 78.0,
    bodySurfaceAreaM2: 1.92,
    location: 'Cardiac Surgical ICU - Bed 03',
    primaryDiagnosis: 'Ischemic Cardiomyopathy s/p High-Risk CABG & Impella 5.5 (Recovery Wean)',
    deviceType: 'IMPELLA_5_5',
    deviceLocation: 'Right Axillary Conduit',
    implantDurationHours: 120, // Day 5
    scaiStage: 'WEANING_TRIAL_CANDIDATE',
    pLevel: 'P2', // Step-down weaning trial
    impellaFlowLitersMin: 1.8,
    motorCurrentMilliamps: 420,
    purgePressureMmHg: 480,
    purgeFlowMlPerHour: 16.5,
    opticalPlacementSignal: 'CORRECT_LV_POSITION',
    lvadSpeedRpm: 0,
    lvadPowerWatts: 0,
    lvadPulsatilityIndex: 0,
    heartRate: 72,
    systolicBp: 116,
    diastolicBp: 74,
    meanArterialPressure: 88.0,
    cardiacOutputTotalLitersMin: 5.2,
    cardiacIndexLitersMinM2: 2.71,
    cardiacPowerOutputWatts: 1.01, // Native CPO reserve > 0.8 W
    pulmonaryArterySystolicBp: 26,
    pulmonaryArteryDiastolicBp: 12,
    centralVenousPressure: 7,
    pulmonaryArteryPulsatilityIndex: 2.00,
    pulmonaryCapillaryWedgePressure: 11,
    lvedpEstimatedMmHg: 9,
    serumLactate: 0.8,
    plasmaFreeHemoglobinMgDl: 14.5,
    ldhUnitsPerLiter: 230,
    antiXaUnitsPerMl: 0.38,
    inotropesVasopressors: 'None',
    suctionAlarmActive: false,
    weaningTrialStatus: 'Weaning Protocol Stage 3 (P2 Trial Passed - Ready for Explant)',
  },
]);
