/**
 * Hospital Command Center & Bio-AI Predictive Patient Deterioration Models.
 *
 * Implements Multi-Parameter Early Deterioration Index (EDI / Rothman continuous trajectory),
 * National Early Warning Score 2 (NEWS2) velocity algorithms, Shock Index dynamics,
 * 12h/24h ICU Escalation Probability AI classifiers, Hospital Capacity Logistics,
 * and Rapid Response Team (RRT) automated activation protocols.
 */

export const ACUITY_LEVELS = Object.freeze({
  CRITICAL_DETERIORATION: {
    id: 'CRITICAL_DETERIORATION',
    label: 'Critical Deterioration (Immediate ICU / RRT)',
    color: 'rose',
    priority: 1,
    description: 'Imminent physiologic collapse or respiratory failure within 2-4 hours. Rapid Response Team / Code Blue dispatch indicated.',
  },
  IMMINENT_ICU_ESCALATION: {
    id: 'IMMINENT_ICU_ESCALATION',
    label: 'High Predictive Risk (ICU Escalation Likely)',
    color: 'orange',
    priority: 2,
    description: 'Elevated 12-hour ICU transfer probability (> 65%). Multiorgan instability or escalating vasopressor/oxygen requirement.',
  },
  UNSTABLE_PROGRESSION: {
    id: 'UNSTABLE_PROGRESSION',
    label: 'Unstable Progression (Early Warning Alert)',
    color: 'amber',
    priority: 3,
    description: 'Negative physiological trajectory with NEWS2 >= 5 or accelerating deterioration index slope. Targeted clinician review required.',
  },
  MODERATE_ACUITY: {
    id: 'MODERATE_ACUITY',
    label: 'Moderate Acuity (Monitored Ward)',
    color: 'cyan',
    priority: 4,
    description: 'Stable but guarded inpatient requiring continuous pulse oximetry, telemetry, and q4h serial vital assessments.',
  },
  CLINICALLY_STABLE: {
    id: 'CLINICALLY_STABLE',
    label: 'Clinically Stable (Low Acuity)',
    color: 'emerald',
    priority: 5,
    description: 'Physiologically compensated with normal vitals and improving biomarker trajectories.',
  },
  STEP_DOWN_READY: {
    id: 'STEP_DOWN_READY',
    label: 'Step-Down / Discharge Ready',
    color: 'teal',
    priority: 6,
    description: 'ICU/PCU patient meeting all de-escalation benchmarks: off inotropes/pressors, weaning oxygen, and stable renal function.',
  },
});

export const HOSPITAL_UNITS = Object.freeze({
  MICU: { id: 'MICU', name: 'Medical Intensive Care Unit (MICU)', capacity: 24, occupied: 22, nurseToPatientRatio: '1:1.5' },
  SICU: { id: 'SICU', name: 'Surgical Trauma ICU (SICU)', capacity: 20, occupied: 18, nurseToPatientRatio: '1:1.5' },
  NEURO_ICU: { id: 'NEURO_ICU', name: 'Neurocritical Care Unit (NCCU)', capacity: 16, occupied: 15, nurseToPatientRatio: '1:1.5' },
  PCU_STEPDOWN: { id: 'PCU_STEPDOWN', name: 'Progressive Care / Step-Down Unit', capacity: 32, occupied: 29, nurseToPatientRatio: '1:3' },
  CARDIAC_TELEMETRY: { id: 'CARDIAC_TELEMETRY', name: 'Cardiac Telemetry Ward (4 East)', capacity: 36, occupied: 31, nurseToPatientRatio: '1:4' },
  MED_SURG_NORTH: { id: 'MED_SURG_NORTH', name: 'General Med-Surg Ward (5 North)', capacity: 48, occupied: 41, nurseToPatientRatio: '1:5' },
  EMERGENCY_OBS: { id: 'EMERGENCY_OBS', name: 'Emergency Clinical Decision Unit (CDU)', capacity: 20, occupied: 19, nurseToPatientRatio: '1:3' },
});

export const RRT_TRIGGER_CRITERIA = Object.freeze([
  { id: 'RR_CRITICAL', trigger: 'Respiratory Rate < 8 or > 28 breaths/min', weight: 3 },
  { id: 'SPO2_CRITICAL', trigger: 'SpO2 < 90% on >= 50% FiO2 or new high-flow requirement', weight: 3 },
  { id: 'SBP_CRITICAL', trigger: 'Systolic Blood Pressure < 90 mmHg or acute drop > 40 mmHg', weight: 3 },
  { id: 'HR_CRITICAL', trigger: 'Heart Rate < 40 or > 130 BPM with new arrhythmia', weight: 2 },
  { id: 'GCS_CRITICAL', trigger: 'Acute reduction in GCS >= 2 points or unexplained lethargy', weight: 3 },
  { id: 'URINE_CRITICAL', trigger: 'Urine Output < 0.5 mL/kg/h for >= 2 consecutive hours', weight: 2 },
  { id: 'LACTATE_CRITICAL', trigger: 'Serum Lactate > 2.5 mmol/L with rising trajectory', weight: 2 },
]);

export const COMMAND_CENTER_PATIENTS_DATABASE = Object.freeze([
  {
    id: 'PRED-101',
    mrn: 'CMD-904128',
    name: 'Arthur Pendelton',
    ageYears: 71,
    sex: 'Male',
    heightCm: 175,
    actualWeightKg: 84.0,
    unit: 'PCU_STEPDOWN',
    bedNumber: 'PCU-14',
    primaryDiagnosis: 'Severe Community-Acquired Sepsis secondary to Pyelonephritis',
    admissionHours: 36,
    acuityLevel: 'CRITICAL_DETERIORATION',
    earlyDeteriorationIndex: 28.4, // Low score indicates high deterioration risk (0-100 scale)
    ediTrend24h: [58.2, 54.0, 48.6, 42.1, 35.8, 28.4],
    icuEscalationRisk12hPct: 88.5,
    icuEscalationRisk24hPct: 94.2,
    news2Score: 10,
    news2Delta4h: 4, // Rapid worsening velocity
    heartRate: 124,
    systolicBp: 86,
    diastolicBp: 48,
    meanArterialPressure: 60.7,
    respRate: 30,
    spO2: 91,
    fio2: 0.50,
    tempC: 38.9,
    gcsScore: 13,
    serumLactate: 3.8,
    wbcCount: 19.4,
    serumCreatinine: 2.3,
    baselineCreatinine: 1.0,
    urineOutputMlPerHour: 18,
    shockIndex: 1.44, // HR 124 / SBP 86 = 1.44 (Severe Shock)
    modifiedShockIndex: 2.04, // HR 124 / MAP 60.7 = 2.04
    activeVasopressor: 'Norepinephrine 0.08 mcg/kg/min titrating',
    rrtStatus: 'RRT DISPATCHED - EN ROUTE (ETA 2 min)',
    topRiskDrivers: [
      { factor: 'Accelerating Tachypnea & Hypoxemic Gap', weightPct: 34 },
      { factor: 'Severe Shock Index & Vasopressor Requirement', weightPct: 28 },
      { factor: 'Lactate Hyperprogression (> 3.5 mmol/L)', weightPct: 22 },
      { factor: 'Acute Oliguria & Creatinine Doubling (KDIGO 2)', weightPct: 16 },
    ],
  },
  {
    id: 'PRED-102',
    mrn: 'CMD-771920',
    name: 'Helena Kowalski',
    ageYears: 64,
    sex: 'Female',
    heightCm: 162,
    actualWeightKg: 68.0,
    unit: 'CARDIAC_TELEMETRY',
    bedNumber: 'TELE-09',
    primaryDiagnosis: 'Acute Decompensated Heart Failure (HFrEF EF 25%) & Pre-Renal AKI',
    admissionHours: 48,
    acuityLevel: 'IMMINENT_ICU_ESCALATION',
    earlyDeteriorationIndex: 41.2,
    ediTrend24h: [65.0, 61.5, 57.0, 50.2, 45.8, 41.2],
    icuEscalationRisk12hPct: 68.0,
    icuEscalationRisk24hPct: 76.5,
    news2Score: 7,
    news2Delta4h: 2,
    heartRate: 106,
    systolicBp: 92,
    diastolicBp: 58,
    meanArterialPressure: 69.3,
    respRate: 24,
    spO2: 93,
    fio2: 0.36,
    tempC: 36.8,
    gcsScore: 14,
    serumLactate: 2.1,
    wbcCount: 11.2,
    serumCreatinine: 1.9,
    baselineCreatinine: 1.1,
    urineOutputMlPerHour: 28,
    shockIndex: 1.15,
    modifiedShockIndex: 1.53,
    activeVasopressor: 'None (Milrinone Infusion planned)',
    rrtStatus: 'CLINICIAN CONSULT NOTIFIED - MONITORING',
    topRiskDrivers: [
      { factor: 'Cardiogenic Decompensation & Hypotension', weightPct: 38 },
      { factor: 'Worsening Cardiorenal Syndrome & Azotemia', weightPct: 30 },
      { factor: 'Elevated Shock Index (> 1.0)', weightPct: 20 },
      { factor: 'Oxygen Desaturation Trajectory', weightPct: 12 },
    ],
  },
  {
    id: 'PRED-103',
    mrn: 'CMD-382901',
    name: 'James Rodriguez',
    ageYears: 53,
    sex: 'Male',
    heightCm: 182,
    actualWeightKg: 91.0,
    unit: 'MED_SURG_NORTH',
    bedNumber: 'MS-22',
    primaryDiagnosis: 'Post-Operative Small Bowel Resection s/p Exploratory Laparotomy',
    admissionHours: 24,
    acuityLevel: 'UNSTABLE_PROGRESSION',
    earlyDeteriorationIndex: 54.0,
    ediTrend24h: [72.0, 69.0, 64.5, 60.0, 56.5, 54.0],
    icuEscalationRisk12hPct: 38.5,
    icuEscalationRisk24hPct: 48.0,
    news2Score: 5,
    news2Delta4h: 1,
    heartRate: 98,
    systolicBp: 108,
    diastolicBp: 68,
    meanArterialPressure: 81.3,
    respRate: 20,
    spO2: 96,
    fio2: 0.28,
    tempC: 38.2,
    gcsScore: 15,
    serumLactate: 1.7,
    wbcCount: 14.8,
    serumCreatinine: 1.2,
    baselineCreatinine: 0.9,
    urineOutputMlPerHour: 42,
    shockIndex: 0.91,
    modifiedShockIndex: 1.21,
    activeVasopressor: 'None',
    rrtStatus: 'STABLE - PROTOCOL MONITORING',
    topRiskDrivers: [
      { factor: 'Post-Op Systemic Inflammatory Response', weightPct: 40 },
      { factor: 'Mild Tachycardia & Low-Grade Fever', weightPct: 32 },
      { factor: 'Mild Leukocytosis Trajectory', weightPct: 28 },
    ],
  },
  {
    id: 'PRED-104',
    mrn: 'CMD-592831',
    name: 'Clara Oswald',
    ageYears: 45,
    sex: 'Female',
    heightCm: 168,
    actualWeightKg: 62.0,
    unit: 'MICU',
    bedNumber: 'MICU-06',
    primaryDiagnosis: 'Resolving Diabetic Ketoacidosis (DKA) & Aspiration Pneumonitis',
    admissionHours: 60,
    acuityLevel: 'STEP_DOWN_READY',
    earlyDeteriorationIndex: 86.5,
    ediTrend24h: [32.0, 48.5, 62.0, 74.0, 81.2, 86.5],
    icuEscalationRisk12hPct: 4.2,
    icuEscalationRisk24hPct: 6.8,
    news2Score: 1,
    news2Delta4h: -2, // Strong improvement
    heartRate: 74,
    systolicBp: 122,
    diastolicBp: 76,
    meanArterialPressure: 91.3,
    respRate: 15,
    spO2: 99,
    fio2: 0.21,
    tempC: 36.9,
    gcsScore: 15,
    serumLactate: 0.8,
    wbcCount: 8.4,
    serumCreatinine: 0.8,
    baselineCreatinine: 0.8,
    urineOutputMlPerHour: 65,
    shockIndex: 0.61,
    modifiedShockIndex: 0.81,
    activeVasopressor: 'None (Weaned off pressors 18h ago)',
    rrtStatus: 'READY FOR FLOOR TRANSFER',
    topRiskDrivers: [
      { factor: 'Anion Gap Closed & Electrolytes Normalized', weightPct: 50 },
      { factor: 'Hemodynamics Fully Stable on Room Air', weightPct: 50 },
    ],
  },
]);
