/**
 * Extracorporeal Liver Support & Acute-on-Chronic Liver Failure (ACLF) Clinical Decision Support Models.
 *
 * Implements EASL-CLIF Consortium ACLF Diagnostic & Prognostic Criteria (CLIF-C ACLF),
 * OPTN MELD-3.0 & MELD-Na scoring, West Haven Hepatic Encephalopathy grading,
 * and MARS (Molecular Adsorbent Recirculating System) albumin dialysis telemetry.
 */

export const ACLF_GRADES = Object.freeze({
  NO_ACLF: {
    grade: 0,
    title: 'No ACLF (Decompensated Cirrhosis)',
    color: 'emerald',
    mortality28d: '< 5%',
    criteria: 'Absence of organ failure, or single non-kidney organ failure without renal/brain impairment.',
  },
  ACLF_GRADE_1: {
    grade: 1,
    title: 'EASL-CLIF ACLF Grade 1',
    color: 'amber',
    mortality28d: '22 - 25%',
    criteria: 'Single kidney failure (Creatinine >= 2.0 mg/dL), OR single liver/coagulation/circulatory/respiratory failure with renal dysfunction (Cr 1.5-1.9) or Grade I/II Hepatic Encephalopathy.',
  },
  ACLF_GRADE_2: {
    grade: 2,
    title: 'EASL-CLIF ACLF Grade 2',
    color: 'orange',
    mortality28d: '32 - 35%',
    criteria: 'Two organ failures (e.g., Liver + Kidney, or Kidney + Brain). Requires immediate ICU evaluation.',
  },
  ACLF_GRADE_3: {
    grade: 3,
    title: 'EASL-CLIF ACLF Grade 3',
    color: 'rose',
    mortality28d: '73 - 78%',
    criteria: 'Three or more organ failures. Severe systemic immune-metabolic breakdown. Emergent extracorporeal liver support (MARS) and expedited transplant listing.',
  },
});

export const WEST_HAVEN_HE_GRADES = Object.freeze({
  GRADE_0: { grade: 0, title: 'No Encephalopathy', description: 'Intact cognition, no asterixis.' },
  GRADE_1: { grade: 1, title: 'Grade 1 HE (Trivial)', description: 'Euphoria or anxiety, shortened attention span, impaired addition/subtraction, mild sleep-wake inversion.' },
  GRADE_2: { grade: 2, title: 'Grade 2 HE (Moderate)', description: 'Lethargy, apathy, minimal disorientation for time/place, subtle personality change, overt asterixis.' },
  GRADE_3: { grade: 3, title: 'Grade 3 HE (Severe)', description: 'Somnolence to semi-stupor, responsive to verbal stimuli, marked confusion, gross disorientation, clonus.' },
  GRADE_4: { grade: 4, title: 'Grade 4 HE (Coma)', description: 'Coma, unresponsive to voice, decerebrate posturing, loss of airway protective reflexes.' },
});

export const HEPATOLOGY_PATIENT_FIXTURES = Object.freeze([
  {
    id: 'HEP-PAT-601',
    mrn: 'LIV-401928',
    name: 'Eleanor Vance',
    ageYears: 54,
    sex: 'Female',
    location: 'Liver ICU - Bed 04',
    etiology: 'Alcohol-Related Cirrhosis & Spontaneous Bacterial Peritonitis (SBP)',
    aclfGrade: 3,
    meld3Score: 38,
    clifCAclfScore: 68,
    mortality28DayEstimated: '78.4%',
    totalBilirubinMgDl: 28.4,
    serumCreatinineMgDl: 3.6,
    inr: 2.9,
    serumSodiumMeqL: 126,
    serumAlbuminGDl: 2.1,
    arterialAmmoniaUmolL: 184, // Normal < 50 umol/L
    westHavenGrade: 3,
    map: 58,
    vasopressor: {
      terlipressinInfusionMgDay: 4.0, // Terlipressin continuous
      norepinephrineMcgKgMin: 0.18,
      status: 'Terlipressin + Albumin protocol for Type 1 HRS-AKI & septic shock',
    },
    marsTelemetry: {
      circuitStatus: 'ACTIVE_RECIRCULATION',
      bloodFlowRateMlMin: 180,
      albuminCircuitFlowMlMin: 180,
      dialysateFlowMlHr: 1000,
      charcoalFilterPressureDropMmHg: 42,
      bilirubinClearancePct: 34.5,
      ammoniaClearancePct: 48.2,
      totalHoursOnMars: 6.5,
    },
    organFailures: [
      { organ: 'Liver', metric: 'Bilirubin 28.4 mg/dL (>= 12.0)', status: 'FAILED' },
      { organ: 'Kidney', metric: 'Creatinine 3.6 mg/dL (>= 2.0)', status: 'FAILED' },
      { organ: 'Brain', metric: 'West Haven Grade 3 (>= 3)', status: 'FAILED' },
      { organ: 'Circulation', metric: 'Norepinephrine + Terlipressin', status: 'FAILED' },
      { organ: 'Coagulation', metric: 'INR 2.9 (>= 2.5)', status: 'FAILED' },
    ],
  },
  {
    id: 'HEP-PAT-602',
    mrn: 'LIV-882190',
    name: 'David K. O’Connor',
    ageYears: 61,
    sex: 'Male',
    location: 'Hepatology Step-down - Bed 12',
    etiology: 'NASH / MASH Cirrhosis with Variceal Hemorrhage',
    aclfGrade: 2,
    meld3Score: 31,
    clifCAclfScore: 54,
    mortality28DayEstimated: '34.2%',
    totalBilirubinMgDl: 16.2,
    serumCreatinineMgDl: 2.4,
    inr: 2.2,
    serumSodiumMeqL: 131,
    serumAlbuminGDl: 2.4,
    arterialAmmoniaUmolL: 112,
    westHavenGrade: 2,
    map: 68,
    vasopressor: {
      terlipressinInfusionMgDay: 2.0,
      norepinephrineMcgKgMin: 0.0,
      status: 'Terlipressin boluses q4h for HRS-AKI reversal',
    },
    marsTelemetry: {
      circuitStatus: 'SCHEDULED_SESSION_2',
      bloodFlowRateMlMin: 150,
      albuminCircuitFlowMlMin: 150,
      dialysateFlowMlHr: 800,
      charcoalFilterPressureDropMmHg: 28,
      bilirubinClearancePct: 29.0,
      ammoniaClearancePct: 41.0,
      totalHoursOnMars: 0.0,
    },
    organFailures: [
      { organ: 'Liver', metric: 'Bilirubin 16.2 mg/dL', status: 'FAILED' },
      { organ: 'Kidney', metric: 'Creatinine 2.4 mg/dL', status: 'FAILED' },
      { organ: 'Brain', metric: 'West Haven Grade 2', status: 'IMPAIRED' },
    ],
  },
  {
    id: 'HEP-PAT-603',
    mrn: 'LIV-310492',
    name: 'Dr. Zachary Thorne',
    ageYears: 48,
    sex: 'Male',
    location: 'Liver ICU - Bed 01',
    etiology: 'Severe Acute Alcoholic Hepatitis (Maddrey DF: 64)',
    aclfGrade: 1,
    meld3Score: 27,
    clifCAclfScore: 48,
    mortality28DayEstimated: '22.0%',
    totalBilirubinMgDl: 22.8,
    serumCreatinineMgDl: 1.8,
    inr: 2.4,
    serumSodiumMeqL: 134,
    serumAlbuminGDl: 2.6,
    arterialAmmoniaUmolL: 88,
    westHavenGrade: 1,
    map: 74,
    vasopressor: {
      terlipressinInfusionMgDay: 0.0,
      norepinephrineMcgKgMin: 0.0,
      status: 'Albumin infusions 1g/kg/day with Prednisolone 40mg PO',
    },
    marsTelemetry: {
      circuitStatus: 'STANDBY_EVALUATION',
      bloodFlowRateMlMin: 0,
      albuminCircuitFlowMlMin: 0,
      dialysateFlowMlHr: 0,
      charcoalFilterPressureDropMmHg: 0,
      bilirubinClearancePct: 0.0,
      ammoniaClearancePct: 0.0,
      totalHoursOnMars: 0.0,
    },
    organFailures: [
      { organ: 'Liver', metric: 'Bilirubin 22.8 mg/dL', status: 'FAILED' },
      { organ: 'Kidney', metric: 'Creatinine 1.8 mg/dL (Dysfunction)', status: 'IMPAIRED' },
    ],
  },
]);
