/**
 * Neonatal Intensive Care Unit (NICU) & Hemodynamics Telemetry Model
 *
 * Implements clinical definitions, reference norms by gestational age,
 * scoring matrices (nSOFA, SNAPPE-II, Sarnat, Bells NEC), and patient fixtures.
 *
 * References:
 * - nSOFA: Wynn JL et al. (Pediatr Res 2020)
 * - SNAPPE-II: Richardson DK et al. (Pediatrics 2001)
 * - Therapeutic Hypothermia for HIE: NICHD Neonatal Research Network Trial Protocol
 * - PPHN Oxygenation Index: AAP / Pediatric Pulmonary Hypertension Network
 * - LISA/MIST Surfactant Protocols: European Consensus Guidelines on RDS (2023)
 */

export const GESTATIONAL_AGE_CATEGORIES = {
  EXTREMELY_PRETERM: {
    id: "EXTREMELY_PRETERM",
    label: "Extremely Preterm (< 28 weeks)",
    minWeeks: 22,
    maxWeeks: 27.9,
    hrRange: [120, 175],
    mapTarget: 26,
    targetSpO2: [90, 95],
    hypothermiaEligible: false,
  },
  VERY_PRETERM: {
    id: "VERY_PRETERM",
    label: "Very Preterm (28 - 31.9 weeks)",
    minWeeks: 28,
    maxWeeks: 31.9,
    hrRange: [115, 170],
    mapTarget: 30,
    targetSpO2: [90, 95],
    hypothermiaEligible: false,
  },
  MODERATE_LATE_PRETERM: {
    id: "MODERATE_LATE_PRETERM",
    label: "Moderate/Late Preterm (32 - 36.9 weeks)",
    minWeeks: 32,
    maxWeeks: 36.9,
    hrRange: [110, 160],
    mapTarget: 35,
    targetSpO2: [92, 97],
    hypothermiaEligible: true,
  },
  TERM_POST_TERM: {
    id: "TERM_POST_TERM",
    label: "Term / Post-Term (>= 37 weeks)",
    minWeeks: 37,
    maxWeeks: 42.0,
    hrRange: [100, 160],
    mapTarget: 42,
    targetSpO2: [94, 99],
    hypothermiaEligible: true,
  },
};

export const HYPOTHERMIA_PHASES = {
  INDUCTION: {
    name: "INDUCTION",
    targetTemp: 33.5,
    minTemp: 33.0,
    maxTemp: 34.0,
    durationHours: 4,
    description: "Active rapid cooling to therapeutic core temperature (33.0 - 34.0°C)",
  },
  MAINTENANCE: {
    name: "MAINTENANCE",
    targetTemp: 33.5,
    minTemp: 33.0,
    maxTemp: 34.0,
    durationHours: 72,
    description: "Steady whole-body cooling with continuous esophageal/rectal telemetry",
  },
  REWARMING: {
    name: "REWARMING",
    targetTemp: 36.5,
    minTemp: 33.5,
    maxTemp: 37.0,
    maxRatePerHour: 0.5,
    durationHours: 12,
    description: "Controlled gradual rewarming (<= 0.5°C / hr) under continuous aEEG monitoring",
  },
  NORMOTHERMIA: {
    name: "NORMOTHERMIA",
    targetTemp: 36.8,
    minTemp: 36.5,
    maxTemp: 37.5,
    durationHours: 24,
    description: "Post-cooling normothermia maintenance avoiding hyperthermia (> 37.5°C)",
  },
};

export const HFOV_DEFAULT_TARGETS = {
  MAP_CM_H2O: { min: 8, max: 24, optimal: 14 },
  AMPLITUDE_DELTA_P: { min: 15, max: 55, optimal: 30 },
  FREQUENCY_HZ: { min: 8, max: 15, optimal: 10 },
  IE_RATIO: "1:2",
  FIO2_PERCENT: { min: 21, max: 100, target: 40 },
};

export const INITIAL_NEONATAL_PATIENTS = [
  {
    id: "NEO-001",
    mrn: "NICU-892401",
    name: "Baby Boy Henderson",
    sex: "MALE",
    gestationalAgeWeeks: 25.4,
    birthWeightGrams: 740,
    currentWeightGrams: 785,
    chronologicalAgeDays: 4,
    correctedGABirthWeeks: 26.0,
    bedNumber: "NICU-POD-A-01",
    incubatorType: "Dräger Isolette 8000 Plus",
    primaryDiagnosis: "Extreme Prematurity, RDS Stage IV, Hemodynamically Significant PDA",
    acuityTier: "CRITICAL",
    respiratorySupport: "HFOV",
    hfovSettings: {
      mapCmH2O: 14.5,
      amplitudeDeltaP: 34,
      frequencyHz: 12,
      fio2: 0.45,
      iToERatio: "1:2",
    },
    hypothermiaStatus: {
      isCooling: false,
      phase: "NONE",
      elapsedCoolingHours: 0,
      targetCoreTemp: 36.8,
      actualCoreTemp: 36.7,
      rewarmingRatePerHour: 0.0,
      aEEGPattern: "CONTINUOUS_NORMAL_VOLTAGE",
    },
    currentVitals: {
      timestamp: new Date().toISOString(),
      heartRate: 158,
      respRate: 48,
      preDuctalSpO2: 94,
      postDuctalSpO2: 86,
      map: 28,
      systolicBp: 39,
      diastolicBp: 22,
      cvp: 4.5,
      coreTempC: 36.7,
      skinTempC: 36.4,
      etCO2: 44,
      paO2: 58,
      paCO2: 52,
      ph: 7.29,
      baseExcess: -4.2,
      lactateMmolL: 2.6,
      plateletsK: 110,
      urineOutputMlKgHr: 1.8,
      glucoseMgDl: 82,
      totalBilirubinMgDl: 6.4,
    },
    medications: [
      { name: "Surfactant (Poractant alfa)", dose: "200 mg/kg (administered day 1)", route: "LISA" },
      { name: "Acetaminophen (IV)", dose: "15 mg/kg q6h", indication: "PDA Closure" },
      { name: "Caffeine Citrate", dose: "10 mg/kg q24h", indication: "Apnea of Prematurity" },
      { name: "Dopamine Infusion", dose: "5 mcg/kg/min", indication: "Inotropic Support" },
    ],
    nSofaScore: 3,
    snappeIIScore: 38,
    oxygenationIndex: 11.2,
    inotropicScoreVIS: 5.0,
    ductalGradient: 8.0,
    bellsNecStage: "STAGE_0_NORMAL",
    sarnatHieStage: "NOT_APPLICABLE",
  },
  {
    id: "NEO-002",
    mrn: "NICU-910243",
    name: "Baby Girl Kowalski",
    sex: "FEMALE",
    gestationalAgeWeeks: 39.2,
    birthWeightGrams: 3420,
    currentWeightGrams: 3380,
    chronologicalAgeDays: 1,
    correctedGABirthWeeks: 39.3,
    bedNumber: "NICU-POD-A-04",
    incubatorType: "Criticool Whole-Body Hypothermia System",
    primaryDiagnosis: "Perinatal Asphyxia, Moderate-to-Severe HIE, Sarnat Stage II",
    acuityTier: "EMERGENCY_COOLING",
    respiratorySupport: "CONVENTIONAL_SIMV",
    simvSettings: {
      pipCmH2O: 22,
      peepCmH2O: 6,
      rateBpm: 35,
      fio2: 0.35,
      tidalVolumeMlKg: 5.2,
    },
    hypothermiaStatus: {
      isCooling: true,
      phase: "MAINTENANCE",
      elapsedCoolingHours: 28.5,
      targetCoreTemp: 33.5,
      actualCoreTemp: 33.4,
      rewarmingRatePerHour: 0.0,
      aEEGPattern: "DISCONTINUOUS_LOW_VOLTAGE",
    },
    currentVitals: {
      timestamp: new Date().toISOString(),
      heartRate: 104,
      respRate: 34,
      preDuctalSpO2: 98,
      postDuctalSpO2: 97,
      map: 46,
      systolicBp: 62,
      diastolicBp: 38,
      cvp: 6.2,
      coreTempC: 33.4,
      skinTempC: 32.9,
      etCO2: 36,
      paO2: 88,
      paCO2: 38,
      ph: 7.36,
      baseExcess: -2.1,
      lactateMmolL: 1.8,
      plateletsK: 165,
      urineOutputMlKgHr: 2.4,
      glucoseMgDl: 94,
      totalBilirubinMgDl: 4.8,
    },
    medications: [
      { name: "Morphine Infusion", dose: "10 mcg/kg/hr", indication: "Shivering Prevention / Comfort" },
      { name: "Phenobarbital", dose: "20 mg/kg IV loading", indication: "Clinical Seizure Control" },
      { name: "Ampicillin + Gentamicin", dose: "Standard renal dosing", indication: "Empiric Sepsis Rule-Out" },
    ],
    nSofaScore: 1,
    snappeIIScore: 22,
    oxygenationIndex: 3.5,
    inotropicScoreVIS: 0.0,
    ductalGradient: 1.0,
    bellsNecStage: "STAGE_0_NORMAL",
    sarnatHieStage: "STAGE_II_MODERATE",
  },
  {
    id: "NEO-003",
    mrn: "NICU-783204",
    name: "Baby Boy Montgomery",
    sex: "MALE",
    gestationalAgeWeeks: 38.0,
    birthWeightGrams: 3100,
    currentWeightGrams: 3050,
    chronologicalAgeDays: 2,
    correctedGABirthWeeks: 38.3,
    bedNumber: "NICU-POD-B-02",
    incubatorType: "Giraffe Omnibed Carestation",
    primaryDiagnosis: "Meconium Aspiration Syndrome, Severe PPHN with Right-to-Left Shunting",
    acuityTier: "CRITICAL",
    respiratorySupport: "HFOV_PLUS_INO",
    hfovSettings: {
      mapCmH2O: 20.0,
      amplitudeDeltaP: 46,
      frequencyHz: 10,
      fio2: 0.85,
      iToERatio: "1:2",
      iNO_PPM: 20,
    },
    hypothermiaStatus: {
      isCooling: false,
      phase: "NONE",
      elapsedCoolingHours: 0,
      targetCoreTemp: 37.0,
      actualCoreTemp: 37.1,
      rewarmingRatePerHour: 0.0,
      aEEGPattern: "CONTINUOUS_NORMAL_VOLTAGE",
    },
    currentVitals: {
      timestamp: new Date().toISOString(),
      heartRate: 168,
      respRate: 58,
      preDuctalSpO2: 95,
      postDuctalSpO2: 79,
      map: 40,
      systolicBp: 56,
      diastolicBp: 32,
      cvp: 8.8,
      coreTempC: 37.1,
      skinTempC: 36.8,
      etCO2: 48,
      paO2: 52,
      paCO2: 54,
      ph: 7.22,
      baseExcess: -7.5,
      lactateMmolL: 4.8,
      plateletsK: 88,
      urineOutputMlKgHr: 0.9,
      glucoseMgDl: 68,
      totalBilirubinMgDl: 5.2,
    },
    medications: [
      { name: "Inhaled Nitric Oxide (iNO)", dose: "20 ppm", indication: "Selective Pulmonary Vasodilation" },
      { name: "Milrinone Infusion", dose: "0.33 mcg/kg/min", indication: "PVR Reduction & Lusitropy" },
      { name: "Epinephrine Infusion", dose: "0.05 mcg/kg/min", indication: "Systemic BP Elevation" },
      { name: "Hydrocortisone", dose: "1 mg/kg q8h", indication: "Vasopressor-Refractory Hypotension" },
    ],
    nSofaScore: 6,
    snappeIIScore: 54,
    oxygenationIndex: 32.7,
    inotropicScoreVIS: 15.3,
    ductalGradient: 16.0,
    bellsNecStage: "STAGE_0_NORMAL",
    sarnatHieStage: "NOT_APPLICABLE",
  },
  {
    id: "NEO-004",
    mrn: "NICU-640192",
    name: "Baby Girl Patel",
    sex: "FEMALE",
    gestationalAgeWeeks: 27.1,
    birthWeightGrams: 890,
    currentWeightGrams: 930,
    chronologicalAgeDays: 14,
    correctedGABirthWeeks: 29.1,
    bedNumber: "NICU-POD-C-03",
    incubatorType: "Atom Infant Incubator V-2200",
    primaryDiagnosis: "Prematurity, Suspected Necrotizing Enterocolitis (Bell Stage IIA), Late-Onset Sepsis",
    acuityTier: "HIGH_RISK",
    respiratorySupport: "NIV_NCPAP",
    cpapSettings: {
      peepCmH2O: 6,
      fio2: 0.30,
      flowLpm: 6,
    },
    hypothermiaStatus: {
      isCooling: false,
      phase: "NONE",
      elapsedCoolingHours: 0,
      targetCoreTemp: 36.8,
      actualCoreTemp: 37.3,
      rewarmingRatePerHour: 0.0,
      aEEGPattern: "CONTINUOUS_NORMAL_VOLTAGE",
    },
    currentVitals: {
      timestamp: new Date().toISOString(),
      heartRate: 172,
      respRate: 64,
      preDuctalSpO2: 93,
      postDuctalSpO2: 92,
      map: 31,
      systolicBp: 44,
      diastolicBp: 24,
      cvp: 3.8,
      coreTempC: 37.3,
      skinTempC: 37.0,
      etCO2: 39,
      paO2: 72,
      paCO2: 44,
      ph: 7.31,
      baseExcess: -4.0,
      lactateMmolL: 3.1,
      plateletsK: 74,
      urineOutputMlKgHr: 1.2,
      glucoseMgDl: 142,
      totalBilirubinMgDl: 8.9,
    },
    medications: [
      { name: "Vancomycin + Meropenem", dose: "Strict IV micro-infusion", indication: "Empiric NEC/Sepsis" },
      { name: "Total Parenteral Nutrition (TPN)", dose: "130 mL/kg/day", indication: "NPO / Bowel Rest" },
      { name: "Normal Saline Bolus", dose: "10 mL/kg over 30 min", indication: "Volume Resuscitation" },
    ],
    nSofaScore: 4,
    snappeIIScore: 42,
    oxygenationIndex: 2.5,
    inotropicScoreVIS: 0.0,
    ductalGradient: 1.0,
    bellsNecStage: "STAGE_IIA_PROVEN_MILD",
    sarnatHieStage: "NOT_APPLICABLE",
  },
];
