/**
 * Pulmonary Critical Care, ARDS & Advanced Mechanical Ventilation Models.
 *
 * Implements Berlin Definition for Acute Respiratory Distress Syndrome (ARDS),
 * ARDSNet Low Tidal Volume Ventilation (LTVV) protocol (4-8 mL/kg PBW),
 * Gattinoni Mechanical Power of Ventilation equation, Driving Pressure thresholds,
 * PROSEVA Trial Prone Positioning protocol, and Rapid Shallow Breathing Index (RSBI).
 */

export const ARDS_SEVERITY_LEVELS = Object.freeze({
  SEVERE_ARDS: {
    id: 'SEVERE_ARDS',
    label: 'Severe ARDS (PaO₂/FiO₂ ≤ 100)',
    color: 'rose',
    priority: 1,
    description: 'Severe refractory hypoxemia with PEEP ≥ 5 cmH₂O. High mortality risk (~45%). Requires ultra-protective ventilation, neuromuscular blockade, and prone positioning or VV-ECMO evaluation.',
  },
  MODERATE_ARDS: {
    id: 'MODERATE_ARDS',
    label: 'Moderate ARDS (100 < PaO₂/FiO₂ ≤ 200)',
    color: 'orange',
    priority: 2,
    description: 'Moderate alveolar-capillary barrier disruption with PEEP ≥ 5 cmH₂O. Lung-protective ventilation (6 mL/kg PBW) and PEEP titration required.',
  },
  MILD_ARDS: {
    id: 'MILD_ARDS',
    label: 'Mild ARDS (200 < PaO₂/FiO₂ ≤ 300)',
    color: 'amber',
    priority: 3,
    description: 'Mild acute hypoxemic respiratory failure with PEEP ≥ 5 cmH₂O. Close monitoring for progression and avoidance of high driving pressure.',
  },
  AT_RISK_LUNG_INJURY: {
    id: 'AT_RISK_LUNG_INJURY',
    label: 'At Risk for Lung Injury / VILI',
    color: 'cyan',
    priority: 4,
    description: 'Mechanically ventilated patient without established ARDS but with elevated mechanical power or high driving pressure (> 14 cmH₂O).',
  },
  WEANING_CANDIDATE: {
    id: 'WEANING_CANDIDATE',
    label: 'Weaning & Extubation Candidate',
    color: 'emerald',
    priority: 5,
    description: 'Resolving pulmonary condition meeting spontaneous breathing trial (SBT) criteria with RSBI < 105 and PaO₂/FiO₂ > 250 on minimal settings.',
  },
});

export const VENTILATOR_MODES = Object.freeze({
  VC_CMV: {
    id: 'VC_CMV',
    name: 'Volume Control Continuous Mandatory Ventilation (VC-CMV)',
    type: 'VOLUME_CONTROL',
    description: 'Pre-set tidal volume delivered with constant or decelerating flow; airway pressure varies based on respiratory system compliance.',
  },
  PC_CMV: {
    id: 'PC_CMV',
    name: 'Pressure Control Continuous Mandatory Ventilation (PC-CMV)',
    type: 'PRESSURE_CONTROL',
    description: 'Pre-set inspiratory pressure delivered with decelerating flow; tidal volume varies with compliance and resistance.',
  },
  PRVC: {
    id: 'PRVC',
    name: 'Pressure-Regulated Volume Control (PRVC / VC+)',
    type: 'DUAL_CONTROL',
    description: 'Target tidal volume delivered with decelerating flow using the lowest necessary inspiratory pressure adjusted breath-by-breath.',
  },
  PSV_CPAP: {
    id: 'PSV_CPAP',
    name: 'Pressure Support Ventilation / CPAP (PSV/CPAP)',
    type: 'SPONTANEOUS',
    description: 'Patient-triggered, pressure-limited, flow-cycled spontaneous breathing mode utilized for weaning and SBT evaluation.',
  },
  APRV: {
    id: 'APRV',
    name: 'Airway Pressure Release Ventilation (APRV / Bi-Level)',
    type: 'OPEN_LUNG',
    description: 'Two continuous positive airway pressure levels with brief time-cycled releases for alveolar recruitment in severe refractory ARDS.',
  },
});

export const PEEP_FIO2_TABLE = Object.freeze([
  { fio2: 0.30, lowerPeep: 5,  higherPeep: 5 },
  { fio2: 0.40, lowerPeep: 5,  higherPeep: 10 },
  { fio2: 0.50, lowerPeep: 8,  higherPeep: 12 },
  { fio2: 0.60, lowerPeep: 10, higherPeep: 14 },
  { fio2: 0.70, lowerPeep: 10, higherPeep: 16 },
  { fio2: 0.80, lowerPeep: 14, higherPeep: 18 },
  { fio2: 0.90, lowerPeep: 16, higherPeep: 22 },
  { fio2: 1.00, lowerPeep: 18, higherPeep: 24 },
]);

export const ASYNCHRONY_TYPES = Object.freeze({
  DOUBLE_TRIGGERING: {
    id: 'DOUBLE_TRIGGERING',
    name: 'Double Triggering / Breath Stacking',
    severity: 'HIGH',
    mechanism: 'Two consecutive ventilator cycles delivered within a single patient inspiratory effort, doubling delivered tidal volume and elevating VILI risk.',
    action: 'Increase tidal volume slightly if < 6 mL/kg PBW, lengthen inspiratory time, or increase sedation/analgesia.',
  },
  FLOW_STARVATION: {
    id: 'FLOW_STARVATION',
    name: 'Flow Starvation / Inadequate Peak Flow',
    severity: 'MODERATE',
    mechanism: 'Ventilator inspiratory flow rate is lower than patient neuro-ventilatory demand, leading to excessive work of breathing and patient distress.',
    action: 'Increase peak inspiratory flow rate (≥ 60-80 L/min) or switch from volume control to pressure control or PRVC.',
  },
  INEFFECTIVE_TRIGGERING: {
    id: 'INEFFECTIVE_TRIGGERING',
    name: 'Ineffective Triggering / Missed Effort',
    severity: 'MODERATE',
    mechanism: 'Patient inspiratory effort fails to drop airway pressure or flow below trigger threshold, common in intrinsic PEEP (auto-PEEP) or weakness.',
    action: 'Optimize PEEP to balance auto-PEEP, decrease trigger sensitivity threshold, or evaluate for dynamic hyperinflation.',
  },
  PREMATURE_CYCLING: {
    id: 'PREMATURE_CYCLING',
    name: 'Premature Cycling / Short Ti',
    severity: 'LOW',
    mechanism: 'Ventilator terminates inspiratory phase before patient neural inspiration finishes, causing diaphragmatic contraction during exhalation.',
    action: 'Decrease expiratory flow cycle threshold in PSV (e.g. from 30% to 15%) or lengthen mechanical Ti.',
  },
  REVERSE_TRIGGERING: {
    id: 'REVERSE_TRIGGERING',
    name: 'Reverse Triggering / Entrainment',
    severity: 'HIGH',
    mechanism: 'Ventilator-delivered mandatory breath triggers a reflex patient diaphragmatic contraction during expiration (neuromechanical coupling).',
    action: 'Adjust respiratory rate, reduce sedation depth, or temporarily initiate neuromuscular blockade in severe ARDS.',
  },
});

export const PRONE_POSITIONING_MILESTONES = Object.freeze([
  {
    id: 'PRE_PRONE_EVALUATION',
    title: '1. PROSEVA Trial Eligibility Screening',
    description: 'PaO₂/FiO₂ < 150 with FiO₂ ≥ 0.60 and PEEP ≥ 10 cmH₂O confirmed on optimized ARDSNet settings.',
    standard: 'PROSEVA / ATS / ESICM Clinical Practice Guidelines',
  },
  {
    id: 'AIRWAY_HEMODYNAMIC_STABILIZATION',
    title: '2. Airway & Hemodynamic Securing',
    description: 'Confirm endotracheal tube depth, secure arterial line & central access, ensure emergency airway cart at bedside.',
    standard: 'SCCM Safety Check',
  },
  {
    id: 'PRONE_TURNING_EXECUTION',
    title: '3. Multi-Person Coordinated Turn',
    description: 'Minimum 4-person team led by respiratory therapist/anesthesiologist at the head; maintain cervical spine alignment.',
    standard: 'ICU Nursing Safety Protocol',
  },
  {
    id: 'MONITORING_16H_SESSION',
    title: '4. 16-Hour Continuous Prone Maintenance',
    description: 'Maintain prone position for at least 16 consecutive hours; alternate head/arm positioning (swimmer position) q2h.',
    standard: 'Lung-Protective Prone Timing Standard',
  },
  {
    id: 'GAS_EXCHANGE_REASSESSMENT',
    title: '5. Post-Turn ABG & Oxygenation Response Check',
    description: 'Perform ABG at 1h, 4h, and 12h post-turn; target Δ(PaO₂/FiO₂) > 20 mmHg or ΔPaCO₂ decrease > 1 mmHg as responder.',
    standard: 'ARDS Physiological Target Benchmark',
  },
]);

export const PULMONARY_PATIENTS_DATABASE = Object.freeze([
  {
    id: 'ARDS-901',
    mrn: 'PULM-482910',
    name: 'Eleanor Vance',
    ageYears: 54,
    sex: 'Female',
    heightCm: 165,
    actualWeightKg: 82.5,
    location: 'Medical ICU - Bed 04 (Isolation)',
    diagnosis: 'Severe Primary Viral ARDS secondary to Influenza A H1N1 Pneumonia',
    admissionDay: 4,
    severity: 'SEVERE_ARDS',
    ventilatorMode: 'VC_CMV',
    setVtMl: 340, // Target 6 mL/kg PBW (PBW female 165cm = 57.0 kg -> 342 mL)
    measuredVtMl: 338,
    setRr: 28,
    measuredRr: 28,
    fio2: 0.85,
    setPeep: 16,
    measuredPeakPressure: 38,
    plateauPressure: 31,
    drivingPressure: 15, // Pplat (31) - PEEP (16) = 15 cmH2O
    staticCompliance: 22.5, // 338 / 15 = 22.5 mL/cmH2O
    autoPeep: 2.1,
    inspiratoryTimeSec: 0.8,
    ieRatio: '1:1.7',
    pao2: 68,
    paco2: 52,
    pao2Fio2Ratio: 80.0, // Severe ARDS (< 100)
    arterialPh: 7.28,
    hco3: 24.1,
    lactate: 2.4,
    spO2: 89,
    heartRate: 112,
    meanArterialPressure: 74,
    mechanicalPowerJoulesMin: 29.4, // Gattinoni high risk (> 27)
    ventilatoryRatio: 2.18,
    asynchronyIndexPct: 14.5,
    primaryAsynchrony: 'DOUBLE_TRIGGERING',
    isProned: true,
    proneHoursElapsed: 9.5,
    proneTargetHours: 16,
    paralyzedNmb: true,
    inhaledVasodilator: 'Inhaled Epoprostenol 30 ng/kg/min',
    ecmoEvaluationStatus: 'VV-ECMO Candidate on Standby (CESAR/EOLIA Criteria)',
  },
  {
    id: 'ARDS-902',
    mrn: 'PULM-839201',
    name: 'Marcus Thorne',
    ageYears: 42,
    sex: 'Male',
    heightCm: 180,
    actualWeightKg: 94.0,
    location: 'Trauma ICU - Bed 08',
    diagnosis: 'Moderate Post-Traumatic ARDS & Pulmonary Contusions s/p High-Speed MVC',
    admissionDay: 2,
    severity: 'MODERATE_ARDS',
    ventilatorMode: 'PRVC',
    setVtMl: 450, // PBW male 180cm = 75.1 kg -> 6 mL/kg = 450 mL
    measuredVtMl: 452,
    setRr: 22,
    measuredRr: 23,
    fio2: 0.55,
    setPeep: 12,
    measuredPeakPressure: 29,
    plateauPressure: 24,
    drivingPressure: 12, // Pplat (24) - PEEP (12) = 12 cmH2O (Target < 14)
    staticCompliance: 37.7, // 452 / 12 = 37.7 mL/cmH2O
    autoPeep: 0.8,
    inspiratoryTimeSec: 0.9,
    ieRatio: '1:1.9',
    pao2: 88,
    paco2: 44,
    pao2Fio2Ratio: 160.0, // Moderate ARDS (100-200)
    arterialPh: 7.36,
    hco3: 24.8,
    lactate: 1.6,
    spO2: 95,
    heartRate: 94,
    meanArterialPressure: 82,
    mechanicalPowerJoulesMin: 18.2, // Moderate risk
    ventilatoryRatio: 1.42,
    asynchronyIndexPct: 4.2,
    primaryAsynchrony: 'FLOW_STARVATION',
    isProned: false,
    proneHoursElapsed: 0,
    proneTargetHours: 16,
    paralyzedNmb: false,
    inhaledVasodilator: 'None',
    ecmoEvaluationStatus: 'Not Indicated - Responding to LTVV',
  },
  {
    id: 'ARDS-903',
    mrn: 'PULM-194830',
    name: 'David Chen',
    ageYears: 67,
    sex: 'Male',
    heightCm: 172,
    actualWeightKg: 78.0,
    location: 'Surgical ICU - Bed 02',
    diagnosis: 'Mild Secondary ARDS post Emergency Peritonitis & Septic Shock',
    admissionDay: 5,
    severity: 'MILD_ARDS',
    ventilatorMode: 'VC_CMV',
    setVtMl: 410, // PBW male 172cm = 67.8 kg -> 6 mL/kg = 407 mL
    measuredVtMl: 408,
    setRr: 18,
    measuredRr: 18,
    fio2: 0.40,
    setPeep: 8,
    measuredPeakPressure: 24,
    plateauPressure: 19,
    drivingPressure: 11, // Pplat (19) - PEEP (8) = 11 cmH2O
    staticCompliance: 37.1,
    autoPeep: 0.5,
    inspiratoryTimeSec: 1.0,
    ieRatio: '1:2.3',
    pao2: 96,
    paco2: 39,
    pao2Fio2Ratio: 240.0, // Mild ARDS (200-300)
    arterialPh: 7.41,
    hco3: 24.5,
    lactate: 1.2,
    spO2: 97,
    heartRate: 80,
    meanArterialPressure: 78,
    mechanicalPowerJoulesMin: 12.8, // Low risk (< 17)
    ventilatoryRatio: 1.15,
    asynchronyIndexPct: 1.8,
    primaryAsynchrony: 'NONE',
    isProned: false,
    proneHoursElapsed: 0,
    proneTargetHours: 16,
    paralyzedNmb: false,
    inhaledVasodilator: 'None',
    ecmoEvaluationStatus: 'Not Indicated',
  },
  {
    id: 'ARDS-904',
    mrn: 'PULM-773829',
    name: 'Sarah Jenkins',
    ageYears: 36,
    sex: 'Female',
    heightCm: 170,
    actualWeightKg: 64.0,
    location: 'Medical ICU - Bed 11',
    diagnosis: 'Resolving Aspiration Pneumonitis - Spontaneous Breathing Trial (SBT)',
    admissionDay: 7,
    severity: 'WEANING_CANDIDATE',
    ventilatorMode: 'PSV_CPAP',
    setVtMl: 0, // Spontaneous mode
    measuredVtMl: 480,
    setRr: 0,
    measuredRr: 16,
    fio2: 0.30,
    setPeep: 5,
    measuredPeakPressure: 13,
    plateauPressure: 11,
    drivingPressure: 6, // Pressure support 6 cmH2O over PEEP 5
    staticCompliance: 58.0, // Normal > 50
    autoPeep: 0.0,
    inspiratoryTimeSec: 0.85,
    ieRatio: '1:2.8',
    pao2: 98,
    paco2: 38,
    pao2Fio2Ratio: 326.7, // Normal / Resolved
    arterialPh: 7.42,
    hco3: 24.2,
    lactate: 0.9,
    spO2: 99,
    heartRate: 72,
    meanArterialPressure: 86,
    mechanicalPowerJoulesMin: 6.4,
    ventilatoryRatio: 0.92,
    asynchronyIndexPct: 0.5,
    primaryAsynchrony: 'NONE',
    isProned: false,
    proneHoursElapsed: 0,
    proneTargetHours: 16,
    paralyzedNmb: false,
    inhaledVasodilator: 'None',
    ecmoEvaluationStatus: 'Not Indicated - Extubation Ready',
  },
]);
